### PR TITLE
UPSTREAM: <carry>: Add vendor/

### PR DESCRIPTION
**Pull request by Fedosin**
It's a common OpenShift practice to have a `vendor` folder with all the dependencies. This allows you not to download dependencies at the time of building the project, but to reuse existing ones.

Generated by `go mod vendor`

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Can we update the description to explain why this is needed? Are we going to need to continually update this? Is this something we could add upstream first?

**Review by elmiko — APPROVED** [review]
i tested this out locally, produced the same out put for me.
/lgtm

**Comment by Fedosin** [comment]
Normally we update `vendor` after each dependency version bump. In short, it must always be consistent with the go.mod file. 
Many upstream projects reject creating `vendor` folder (as I know, no one adds it), so it's not a requirement for us that the upstream repo must contain `vendor` inside.

**Pull request merged**
