### PR TITLE
Rebase onto latest upstream version

### PR DESCRIPTION
**Pull request by RadekManak**
Rebased by rebasebot on top of upstream master, includes #34, manually squashed commits, includes downstream version of https://github.com/kubernetes/cloud-provider-alibaba-cloud/pull/356, manually created vendor commit.

### CODE REVIEW

**Comment by sunzhaohua2** [comment]
Run regression with pr [276](https://github.com/openshift/cluster-cloud-controller-manager-operator/pull/276) and [35](https://github.com/openshift/cloud-provider-alibaba-cloud/pull/35) all cloud team cases passed, result [golang](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/ginkgo-test/209673/console) and [cucushift](https://mastern-jenkins-csb-openshift-qe.apps.ocp-c1.prod.psi.redhat.com/job/ocp-common/job/Runner/868732/console)  
/label qe-approved

**Comment by JoelSpeed** [comment]
/approve
/lgtm

Based on QE testing, lets get this merged

**Pull request merged**
